base: &base
  adapter: postgresql
  encoding: utf8
  reconnect: false
  username: stephan.hagemann
  host: 127.0.0.1
  password:

development:
  database: foos_development
  <<: *base

test:
  database: foos_test
  <<: *base

production:
  database: foos_production
  <<: *base

